### ISSUE TITLE
[Bug] Mesh in Chrono maps doesnt seem to work right on cliffs

### ISSUE THREAD

**Issue by empZealoth** [KnuckleCracker/CW4-bug-tracker#1013]
I've been playing the daily maps and there seems to be an issue where creeper can't traverse steep cliffs with mesh on them
At least I assume that was the point of the mesh in this map (Nov 25,2021) - to have creeper leak onto "my" side?

![obraz](https://user-images.githubusercontent.com/10992509/143688713-d09a5a11-92e0-4a87-a127-2b4213da0c6e.png)

**Comment by grabz-dev** [comment]
This is not a bug. What happened in the terrain generator for this map is that a patch of resource ground spawned, cutting through that mesh piece. Resource terrain seems to be coded in a way where the generator does not create it on void, making the mesh appear like it should be connecting, but it actually has no connection to the mainland, because all the cells on the mainland have been taken up by resource ground.

![image](https://user-images.githubusercontent.com/51026936/143722793-c4888529-9f4a-4e1b-9795-30c36f2731c3.png)

**Comment by empZealoth** [comment]
> This is not a bug. What happened in the terrain generator for this map is that a patch of resource ground spawned, cutting through that mesh piece. Resource terrain seems to be coded in a way where the generator does not create it on void, making the mesh appear like it should be connecting, but it actually has no connection to the mainland, because all the cells on the mainland have been taken up by resource ground.
> 
> ![image](https://user-images.githubusercontent.com/51026936/143722793-c4888529-9f4a-4e1b-9795-30c36f2731c3.png)

But isn't that unwanted behaviour? To me it clearly seems that the mesh was supposed to go across the void.
Wouldn't it be better to prevent ore spawns on mesh, if they override them anyway?

**Comment by grabz-dev** [comment]
> But isn't that unwanted behaviour? To me it clearly seems that the mesh was supposed to go across the void.
Wouldn't it be better to prevent ore spawns on mesh, if they override them anyway?

Well now that's a different discussion; I was explaining how the game itself is working properly as this issue is titled "mesh doesn't seem to work right on cliffs" which is false as there is no mesh on the cliff. I suppose the issue stands as a chronom map generation quirk though.

**Comment by empZealoth** [comment]
Should I remake this as a better worded issue?
I'm not very good at this whole GitHub thing lol
