### ISSUE TITLE
[Bug.Minor] SetUnitCanMove prevents deselection of some units

### ISSUE THREAD

**Issue by Fireswamp** [KnuckleCracker/CW4-bug-tracker#1044]
Using the code:
SetUnitCanMove(99 true)
where 99 is the unit ID of a base game unit that normally cannot be moved.  After this, select the unit and the unit can no longer be deselected; I tried clicking on other units, cancel hotkey, SetUnitSelected(99 false), and destroying the unit to no success.  Units can still be built using hotkeys, and other units can still be selected with shiftclick, but prevents use of top left menu for other unit types.  This state can be fixed by saving and loading.

I tested this with the following units, all exhibiting the same behaviour:
Emitter, Spore Launcher, Blob Nest, Dark Tower, Crystal, Bluite, Totem, UltraCap, Resource Pod, Infocache, 5x5 Panel.

**Comment by knucracker** [comment]
The problem was once one of those units was selected, it didn't have a legal movement ghost.  The game never defined movement ghost images for all of those units.  So, one set to movable and selected an exception was being thrown.

I've added a generic movement image as a catchall for any unit that doesn't have one defined.  This allows these units to be selected and moved now.
