### ISSUE TITLE
[Bug.Minor] Unselectable unit specified targets can be selected when a specified target is already selected.

### ISSUE THREAD

**Issue by VertuTheMapMaker** [KnuckleCracker/CW4-bug-tracker#1049]
If there are units that are unselectable, they can still be selected via their specified target if another unit with specified target is already selected.
Just simply select a unit(s) with specified target then click the unselectable unit's specified target, it appears that when a specified target is selected, the game sets all specified targets to be selectable and it can even be hard to deselect the unselectable unit's specified target once selected via this bypass but after clicking with the unselectable specified target as the last specified target to be placed, the unselectable specified target will be successfully placed like any normal specified target. This also applies to Porters.

The unit itself is not selected, only the specified target. This is very annoying for units such as my VAUs which use the specified target to position themselves and during Play As Creeper with Porters around. Luckily not many players know if this bug to then exploit in such maps though my mentioning of it here my change that.
Feels like an oversight so in theory it should be rather easy to fix. Thank you.

**Comment by knucracker** [comment]
Fixed.  I've also changed it so that the gray target indicator line shows for only 2 seconds after a game is loaded (if a specified target indicator is set naturally).  This prevents a non-selectable unit with a specified target from showing a  gray arc line forever.  I've also changed it so when a specified target is set with the mouse, a gray line persists for 1 second.  This is just a cosmetic change.
