### ISSUE TITLE
[Bug] 5x5 units can be placed in a way so they clip through each other using drag build

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#1057]
https://user-images.githubusercontent.com/51026936/183452030-fe0b58ce-8ae5-4bc6-a1c7-725ec4b16e1a.mp4

This works for all 5x5 units (e.g. Porter)
![image](https://user-images.githubusercontent.com/51026936/183452227-dc6cbc22-c857-486f-a1a7-3d166912b06e.png)
Does not work on 7x7 units.

**Comment by knucracker** [comment]
Fixed in 2.4.2.  Changed the logic so it added extra padding on 5x5  units. Had to do with sqrt(5*5+5*5)=50  and integer cell distances (which worked out to 49 in this case).  Also noted that custom units were totally wacked.  Changed them to use the "-1" internal algorithm that calculates the proper placement distance.  That should make custom unit drag placement better.
