### ISSUE TITLE
[bug] A newly built Terp on any mission has its ammo set to -29/30 after receiving the first ammo packet

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#115]
When a Terp receives its first ammo packet, its ammo counter gets set to -29/30, meaning 30 packets are wasted into the Terp before it starts collecting ammo:
![image](https://user-images.githubusercontent.com/51026936/98602961-8d631900-22e1-11eb-82ab-1e7f2174a326.png)

**Comment by knucracker** [comment]
Fixed it so that the drone does not borrow from the pad anymore causing it to go negative. I also made it so that the drone gets a full load of ammo when the pad finished building. That allows the drone to immediately take off after the pad finishes building.  The pad then of course has 0 ammo, so it will load up with 30 ammo ready for the drone when it returns.
