### ISSUE TITLE
Ammo of sprayer is more than full

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#131]
This sprayer was newly built on War and Peace 
![image](https://user-images.githubusercontent.com/16858356/98713737-4419d480-2388-11eb-9185-e74b4e7a83e5.png)

**Comment by knucracker** [comment]
The sprayer  (or any unit that took a ware) were overfilling rather than underfilling. Packets supply 1 unit of a ware, but the sprayer consumes fractional amounts. So as soon as the sprayer spent 0.2 it would then ask for a packet. That would take it to 20.8.  For energy I was only asking for a packet once the entire packet was needed. So I would only ask for a packet when the ammo was at 19 or less.  I've changed wares to act the same as energy.
