### ISSUE TITLE
[Bug.Minor] Runway, Bomber and AC Bomber unit ghosts look very low quality

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#145]
Ghosts look low quality:
![image](https://user-images.githubusercontent.com/51026936/98790994-b7612c00-2404-11eb-91cf-647bf3402922.png)
Units look normal:
![image](https://user-images.githubusercontent.com/51026936/98791044-c6e07500-2404-11eb-91b1-6c4fdfb21564.png)

**Comment by knucracker** [comment]
Really odd... has to do with AA (antialiasing) being turned off.

**Comment by knucracker** [comment]
So it looks like I had the AA setting (when set to off) also changing the master texture quality. It was cutting it in half. So that was dropping the textures used by the remaining voxel units in half.  I've removed this for beta 2, so the texture should stay at a higher quality for the voxel units when AA is off.
