### ISSUE TITLE
[bug] Reloading a save heals energy walls (such as those on the Hints Farsite mission) back up to full

### ISSUE THREAD

**Issue by GrandTeki** [KnuckleCracker/CW4-bug-tracker#169]
Before
![image](https://user-images.githubusercontent.com/50800712/99109299-e46e3400-25e8-11eb-86a9-ba2f87a4793a.png)

After
![image](https://user-images.githubusercontent.com/50800712/99109321-ed5f0580-25e8-11eb-8af9-f110b01266d7.png)

**Comment by knucracker** [comment]
The power was being saved and loaded correctly by the wall. The issue was that it was getting reset to 100% in the Start function.  I added a check to only do this for a brand new wall. That way a wall just placed has 100% health and any other wall will get whatever it's persisted state is  (and keep it).
