### ISSUE TITLE
[bug] Overseer footprint when being moved is smaller than the actual unit

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#19]
The new overseer unit seems to occupy a 5x5 space, but the footprint for it while being moved only occupies a 3x3 space. This allows you to place units in positions which overlap with the overseer. You can see in the following screenshot that I am able to place towers right beside the overseer while the overseer is hopping up into the air:
 
![overseer1](https://user-images.githubusercontent.com/32053682/93300317-2aab4080-f7bc-11ea-8cda-945b4b515d05.png)

And in the next screenshot, you will see that once the overseer is landed I am unable to place an additional tower the same distance as the previous towers, although the previous towers are still active:

![overseer2](https://user-images.githubusercontent.com/32053682/93300437-6219ed00-f7bc-11ea-92ba-be6c098b9c74.png)

**Additional context**
The rift lab placement seen in the screenshots is also only possible due to the bug. Normally you shouldn't be able to land a rift lab on that ledge around the overseer.

**Comment by Karsten75** [comment]
Hmm - I thought the Overseer was not supposed to be movable by the player?

**Comment by knucracker** [comment]
Yeah, the overseer isn't supposed to be movable. The problem was I changed that the last two missions in the demo (the final two bonus missions being the only ones to have the overseer) originated before I made the change to make the overseer unmovable.  So they had been saved with it in a movable state. I've re-finalized the missions after deleting and recreating the overseer on each of those two missions.
