### ISSUE TITLE
[bug] Log with unexplained errors

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#194]
Was looking for a log file to accompany another bug report when I came accross these issues, THought it may be useful to at the very least preserve the log output. 
Best I can tell, it was a challenge mission on Map Before Time in Span 

[output_log02.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5542753/output_log02.txt)

**Comment by knucracker** [comment]
The exception came from a pterosaur attempting to find a new tree. Might have happened after it was dead already. I have added a check that if dead, don't look for a new tree (might happen on final update). I've also added a try/catch around the sort of nearby trees. And I enhanced the sort just a tad so that it handled trees that are equidistant.  Perhaps the combination of all three will make this go away.
