### ISSUE TITLE
[Bug] Hold base remaining green when submerged in Creeper

### ISSUE THREAD

**Issue by TacisLexica** [KnuckleCracker/CW4-bug-tracker#200]
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5544954/output_log.txt)
![cw4ss_1](https://user-images.githubusercontent.com/37869748/99228657-a5ceb880-2838-11eb-8b53-8ce06a6311f1.jpg)

After finishing this mission, I let the game run with no weapons. As I went to close the map, I noticed that one of the hold base markers is showing up as green.

As far as I know, that hold base had never been submerged, but that isn't a condition unique to it.

I'm using a starch-based machine at the moment, so playing back through with a low frame rate is not an appealing thought.

**Comment by grabz-dev** [comment]
You should probably zip up and post the map save file for this one.

**Comment by Regallion** [comment]
This is a much weirder bug that it seems.

[OddHoldem.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5546279/OddHoldem.zip)

So here are the steps:

1. Start the mission
2. Set it to 4x
3. Wait
4. Once 3/4 bases are captured you will get "Objective lost" notification
5. The last base will not turn red.
6. Once you load (you can use the save) all bases will be green and remain green. The objective will be red.

**Comment by knucracker** [comment]
There were two problems. The first was that after the objective was lost, the hold bases stopped updating their status. So they would not turn red or heal. That is fairly minor, but I have changed it so that hold bases that aren't already red can still turn red after the objective is lost.  No hold base will heal after the objective is lost, though.

The second issue was that the hold bases were not persisting their charge state. So after a save and load, they would return to 100%.
