### ISSUE TITLE
Walls can build squads

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#21]
When selecting several walls, you have the option to build and select squads - I don't think this would be ever useful but I might be wrong.

**Comment by knucracker** [comment]
You can toggle the "Blocks AC" option on walls. That can be used to selectively let AC out of a contained area (you can do this on the final mission of the demo if you get in trouble on the main island). Since you might want to do that on only select wall segments, I left the option in to create squads out of walls. That allows you to pick the walls you want to toggle, squad them, then recall them easier.  Of course if I had hotkeys for squads it would be even easier....
