### ISSUE TITLE
[Bug] Eggs behave in weird way when the spore launcher is covered by shield.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#222]
Load this save file.

[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5553198/save.zip)

Unpause.

![image](https://user-images.githubusercontent.com/40322714/99386298-4bd6fd00-28e3-11eb-919c-111f5cbc536e.png)

I cannot even begin to classify what is going on.

Special note - once the shield gets destroyed, the eggs will remain in formation and will SLOWLY fall to the ground.

**Comment by Karsten75** [comment]
Eggs are bound by a bond to their destination and also, to some extent, by bonds or interactions between themselves. I shield tensds to repel them, and what you observe may be the normal interaction between them in this context.

**Comment by knucracker** [comment]
This is a result of many eggs emitted at once, bound to each other. It's similar to snakes and other interesting artifacts that can show up in Particle Fleet. The eggs have a repulsion and attraction (based on bonds). When there are too many to fit in a given area, you get simulation artifacts.  It's know, and 'desirable' since it can make really odd things. If a map doesn't want the effects, then it should not emit the amount of eggs that trigger it.  Different effects are obtained by emitting different amounts of eggs.
