### ISSUE TITLE
[Bug.Minor] Totem with "NONE" type of repair ware cannot be repaired

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#224]
![image](https://user-images.githubusercontent.com/40322714/99389667-6f507680-28e8-11eb-95c9-eb0a91a0ed7d.png)

**Comment by knucracker** [comment]
This is reserved for 4rpl based totem activation. You can't do it in 4rpl right now, but that's what it is reserved for. What I did was hide the "needs" part of the popup when the totem is set to None.  So in the future when there is some 4rpl control over a totem, it will be up the other mission text, etc. to make clear why the totems come and go (because of player action, or they cycle on their own, etc).
