### ISSUE TITLE
[Bug.Minor] Editor - delete eggs is equivalent to pop eggs

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#225]
1. Open editor.
2. Cause a bunch of eggs to be spawned
3. Press "Delete eggs"

Expected: eggs are removed with no other effect
Actual: eggs act like they've been popped, releasing creeper.

**Comment by Karsten75** [comment]
The creeper can be removed afterwards by "delete Creeper" or by painting zero creeper (or any desired amount of) creeper over them. This way there is a mechanism to have creeper deposited on the map by eggs at will.

**Comment by knucracker** [comment]
Since I have delete and pop eggs as separate buttons, I fixed the delete eggs to be different than pop eggs.  Delete will remove the eggs without depositing creeper regardless of the "pop on destroy" option configured on the egg.  Pop will do the opposite. It will deposit the eggs payload even if the egg is told to not deposit payload on destroy.
