### ISSUE TITLE
[Performance] Lower framerate than perhaps expected

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#228]
So I've been messing around with the Creeper++ mission in the span and I overbuilt on mortars a significant amount, making the game laggy. What I didn't expect though is that after deleting most of the mortars, the game still kept to lower FPS. It seems that the biggest lag source in this one is actually the full map being coated in AC, but slowly removing each of the three emitters and their corresponding defense force does seem to bring the performance back up. I think it's just an issue of my dated hardware, but it might be worth profiling these maps. The first save is filled with a ridiculous amount of mortars, the second is much more reasonable but the performance between the two is not much different for me.

[Grabz - Creeper++.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5553736/Grabz.-.Creeper%2B%2B.zip)

**Comment by knucracker** [comment]
So there are two things going on. The first is there is just a lot going on.  With a full map covered in AC/Creeper that will stress the CPU to GPU bridge because all of that geometry has to be updated.  There are also a lot of units still on this map, and they are doing their fair share.  

The second thing, and this is why it is good to look at these things, is there was smoking gun. It had to do with the shields. All shields (shields or totems) were constantly redeploying themselves. The routine was as efficient as it could be, but it was still a lot of work that didn't have to happen. The shields thought they were being moved because of mismatch in how their height was calculated. In profiling on this mission save (the 6 one) they accounted for 16% of the game load per frame. After fixing them, that disappears.  On worse hardware, that 16% might have been higher.

Here is how things profile now:
![image](https://user-images.githubusercontent.com/6733225/99425452-d9f5b800-28d0-11eb-9b58-744142e7a356.png)
