### ISSUE TITLE
[Bug.Minor] Lab rematerialization small visual bug

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#234]
If a map is saved and loaded after the lab is placed, the rematerialization visual animation doesn't play.

1. Launch a map
2. Place rift lab while the game is paused
3. Save and load
4. Unpause

**Comment by knucracker** [comment]
The lab was persisting everything properly. It was just just explicitly setting dematerialize after rematerialize. That was forcing the wrong material on the unit. I changed it so that setting dematerialize or rematerialize only takes an action if the state is changed (and they both default to false on a load).
