### ISSUE TITLE
[Bug] Chanson 4RPL units don't produce more units when said units reach cap

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#235]
**Describe the bug**
Chanson 4RPL pads stop producing units. Suspect that it hits the cap and permanently stops.

**Comment by knucracker** [comment]
The patrol script on the gliders was not updating the patrolCount on the base properly. I had added Get/SetScriptVar apis where the 2nd argument could be an empty string. The 2nd argument specifies the script, by name, on the unit to set the script var on. If left blank, then the first script will be used. I had put 0 rather than "" for the script name.
