### ISSUE TITLE
[Bug] Porters do not transport wares

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#237]
build a porter new some resources (bluite, Redon)

The porter will not load and transport the resource to the factory. 

Connect the porter to the rift lab/factory. A number of packets (yellow) travel from the factory to the porter

Once this has completed, break the connection between the porter and the rift Lab/factory

the porter(s) will now accept resource and transport them to the factory. 

Even if the porters are not connected to the rift lab/factory, providing a resource pod does NOT seem to satisfy this requirement

**Comment by knucracker** [comment]
This problem was introduced by the change in beta 4 that prevents pods from supplying porters. The issue is that once the porter pad finishes building it then attempts to build the drone. This is a separate phase and requires energy. But at that point the porter isn't allowing reception of anything from a pod (including the energy it needed to build the drone).

Another problem; Drones can be destroyed, and when they are the pad will rebuild one. However it needs energy to do that. If the pad was set to something other than energy, the drone would not rebuild since the pad was asking for something other than energy.

The fix: I don't see why the drones need to be paid for separately. I've increased the cost of the deliver pad from 25 to 40 and made the cost of the drone 0 (insta build). It's a rare thing that the drone gets destroyed and when it does, you will just get a new free one at the pad. This of course solves this particular problem since the drone doesn't need energy and the porter pad becomes operational after it has completed building.
