### ISSUE TITLE
[Bug]Nullified Dark Tower remains inactive after nullifier lost

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#238]
Nullify a dark tower,

Lose the nullifier

Dark Tower remains inactive
Save and recorder files 

[dark tower nullify.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5557982/dark.tower.nullify.zip)

**Comment by Karsten75** [comment]
![image](https://user-images.githubusercontent.com/22965021/99488104-48686380-292d-11eb-8dc4-71ff30046f0b.png)


The emitter indicated has also been nullified and then lost it's nullifier. Different than units that are first nullified, it does not return to the "nullified" status in the mini-map.

**Comment by knucracker** [comment]
Looks like that dark tower is almost totally surrounded by beacons. Only in the very top left of its range can you see the darkness. I just loaded the save and confirmed it is the beacons that are removing almost all of the dark area. That's why it appears to have not reactivated.

On the minimap it has  turned red, which indicates it is not nullified. If I built a new nullifier it turns orange indicating it is nullified. If I blow that nullifier up, it will turn red on the minimap again.

Unless I'm missing some detail, the 99% beacon coverage probably caused the initial perception of a problem
