### ISSUE TITLE
[Bug.Minor]Two airships can overlap (occupy the same space)

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#239]
![image](https://user-images.githubusercontent.com/22965021/99489798-258a7f00-292e-11eb-956f-b0f49788fba6.png)

Not sure about this one, but pointing it out, just in case.

**Comment by knucracker** [comment]
yeah, the alternative is to have them prevent each other from coming with range of each other (their length range). That likely would require a different way of accounting for their location and checking (since I don't want them taking space on the ground). That would in turn require some way to handle target positioning from 4rpl and do the check against all airships as the target indicator is moved. And that in turn would likely produce a solution that the player found less satisfying. So I'll punt this one and leave it to players to stack or not stack airships.

All that said, the stuff about 4rpl and target legality is still a legit thing to do in general. So I'll move this to the 4rpl tag and let it live there for a while
