### ISSUE TITLE
[Bug]  All objective scores not submitted

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#240]
![image](https://user-images.githubusercontent.com/22965021/99494213-3f2fc480-2936-11eb-96b5-c05c4e7c9c06.png)

Note that the "collect" score is not mine, although I got it and submitted the scores. I can only hypopthesize that scores obtained before a save were not submitted. 

I have some save files, but not sure if they will be helpful.

**Comment by grabz-dev** [comment]
A similar thing happened to me on the Creeper++ map. I had previously completed it back when it only had two objectives. Then the map was updated to have four objectives. I started over from the main menu, and played through the map. Upon completion, the game only let me submit scores for the two new objectives. The other two "already completed" objectives had green checkmarks before hitting submit. The game must've somehow thought the save had already submitted scores for these objectives, when that was most definitely not the case.

**Comment by knucracker** [comment]
The game was not remember the acquiredObjectiveTime within  a save. . It was a subtle interplay between not storing the data and how I compare against it.  When an objective is obtained, the game remembers the timestamp (the real world time stamp) that the objective was obtained. If a post to the play log is made, that "acquiredObjectiveTime" gets remembers for that objective on that map. It gets stored in the mcs.dat file.  If at any future time the submission dialog is brought up for the same map, the acquiredObjective that is stored in the mcs.dat file will be compared against the acquiredObjectiveTime in the game instance. If they match, then that objective has already been submitted.  If they differ, it is because a new acquiredObjectiveTime has been obtained because the player played the mission again.

This system seems to work, but only if I store the acquiredObjectiveTime in the save game file. Otherwise, when the game loads it will load up records of previously acquired objectives, and their 'acquiredObjectiveTime' filed will be 0.
