### ISSUE TITLE
[Bug] CTD when using a spore tower

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#241]
1. Enter editor
2. Place spore tower
3. Set initial delay and spore timer to 0 (shorthand for "disabled" usually)
4. Apply
5. Hover over the tower.

Game crashes.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5559299/output_log.txt)

**Comment by knucracker** [comment]
A divided by zero slipped past me. Divide by zero will cause a hard crash in an IL2CPP application since I have dbz checking turned off (for runtime efficiency). It was in the popup when it was attempting to calculate the interval time. The popup handlers for the spore launcher, skimmer factory, blob nest, and airsac cauldron all had the same problem. I changed it to protect against divide by zero and also changed the popups so they detect zero and show "no spores" when the interval is zero.
