### ISSUE TITLE
[Bug] Cannot close Upload map dialog

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#262]
1. Open upload map dialog.
2. Can't close it.

This occurred when pressing Upload on an already-uploaded map.

![image](https://user-images.githubusercontent.com/40322714/99717824-fc4b2980-2aba-11eb-89db-cefa92da115c.png)

**Comment by Regallion** [comment]
The log also contained this:

Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 38277.
Total: 165.283900 ms (FindLiveObjects: 6.788000 ms CreateObjectMapping: 1.964900 ms MarkObjects: 156.398600 ms  DeleteObjects: 0.131500 ms)

Coroutine couldn't be started because the the game object 'FinalizedList' is inactive!
FinalizedMapsManager:InvokeNextFrame(Function)
FinalizedMapsManager:RefreshList()
UploadMapManager:OnInfoPanelClosed()
Function:Invoke()
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.Events.UnityAction`2:Invoke(T0, T1)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMousePress(MouseButtonEventData)
UnityEngine.EventSystems.StandaloneInputModule:ProcessMouseEvent(Int32)
UnityEngine.EventSystems.StandaloneInputModule:Process()
UnityEngine.EventSystems.EventSystem:Update()

[ line 783] 
(Filename:  Line: 783)

**Comment by knucracker** [comment]
The upload response was attempting to refresh the old finalized list pane (back when there were two). That was causing that error message in the log. Because of this, the actual map list was not refreshing and continued to show an upload button. That in turn allowed the double upload attempt.

After the fix the list properly refreshes and the upload button is no longer available. If the button is brought back (the same map is attempted from another machine for instance), an error message is shown to the user and the resulting dialog has the proper cancel to dismiss the upload page.
