### ISSUE TITLE
[Bug.Minor] Steam doesn't recognise when CW4 closes if it opened N++ from the editor.

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#264]
**Describe the bug**
Steam thinks CW4 is still running if:
1. CW4 opened N++ from inside the editor, when editing a script
2. and then CW4 closes but N++ is still open
Steam remains thinking CW4 is still open until N++ closes, preventing relaunch.

**Additional context**
Particle Fleet also has this problem, which is why I have it labeled as minor. The workaround is just either starting N++ separately or closing it out when the issue occurs.

**Comment by Karsten75** [comment]
A thought occurred to me that it may at the very least be possible to put  a warning on the exit dialog to remind the player that an application was spawned and needs manual close.

**Comment by jtAZ5** [comment]
I have the same problem, but it does not require any external app to be opened from CW4

I can repeat the problem as follows:

1. reboot computer
2. start Steam
3. start CW4
4. exit CW4 straight from the menu screen without doing anything else

--> Steam says that CW4 is running, and clicking "stop" on steam does nothing

5. exit Steam - Steam messages "Waiting for CW4 to shut down..." and asks whether to exit now or cancel --> exit now
6. restart Steam
7. start CW4
8. exit CW4 from menu screen

--> same issue
Clicking Stop in Steam while CW4 is running --> same issue

**Comment by Durikkan** [comment]
Also worth noting, this bug also holds the game open if you open the help mid-game until you close the web browser.  That one is a lot less obvious what the issue is beforehand.

(Was originally going to post this on the discord but noticed this matched the same formula so decided to add on to it so it doesn't get lost in the noise there, and just including what I originally typed here for completeness)

Was playing, opened the help option in a web browser.  Finished playing, came back and tried to start the game again and it was already running.   Clicking stop didn't do anything.  Long story short, the web browser, which was still open made it think I was still playing CW4, so I had to close that out to start the game again, even though that was no longer pointed at anything creeper related.  So it thought the web browser was part of CW4.

**Comment by rollerce** [comment]
Bumping with a general agreement to the above. The weird thing, I think the bug is also draining the hell out of my laptop battery...

**Comment by Karsten75** [comment]
Seems this is an insurmountable issue.
