### ISSUE TITLE
[Bug.Minor] "Downloaded" filter is misleading

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#265]
Colonies.

Downloaded filter simply means "Maps you have ever clicked on in the colonies". This is a bit misleading and somewhat questionably useful. 
This is different from CW3 where you had to explicitly download maps and thus could at least somewhat curate that list.

**Comment by knucracker** [comment]
I think the primary use case is when you are disconnected (like on a laptop on a plane). The game should fallback to it's last refresh of the maps from the server in that case. But since you can't load any new maps, you would want to only see the maps you already had a local copy of.  That's the theory anyway.
