### ISSUE TITLE
[Bug]Attempting to close the game then cancelling can softlock the game

### ISSUE THREAD

**Issue by cornucanis** [KnuckleCracker/CW4-bug-tracker#266]
Basically if you try to ALT+F4 in the main menu then cancel and go to Colonies it can freeze your game. Here are the steps to repro:

1. Start game and go to Colonies to load the map list
2. Return to main menu
3. Press ALT+F4
4. Click cancel when the confirmation dialog pops up
5. Go back to Colonies
6. Game should now be stuck trying to refresh map data

Additional notes: Oddly enough, the game doesn't seem to lock if you omit steps 1 and 2 and instead simply press ALT+F4 as soon as you load the game.

**Comment by cornucanis** [comment]
Here is the associated log file, nothing seems to be amiss at first glance

[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5569544/output_log.txt)

**Comment by knucracker** [comment]
This turns out to be relevant.
https://issuetracker.unity3d.com/issues/onapplicationquit-method-is-called-before-application-dot-wantstoquit-event-is-raised

So the issue is caused by the HTTP package I use hooking the OnApplicationQuit function. That gets fired even though I intercept the application shutdown.

To solve, I disable the OnApplicationQuit in the http package, then on actual exit I manually call that packages OnQuit() function.
