### ISSUE TITLE
[bug] In Creeper++ maps, emitter values can exceed maximum possible settings.

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#27]
![image](https://user-images.githubusercontent.com/22965021/93670528-ad085e80-fa61-11ea-9b54-17ddc0de3a50.png)

In the attached screenshot it can be seen that the emitter is specified to emit 10,000
![image](https://user-images.githubusercontent.com/22965021/93670737-2eacbc00-fa63-11ea-97e2-a83bc9788cd0.png)

WHile I would prefer a ramp-up of emitters over the number of Creeper++ intervals, I don't think that's simle to implement, so I'd settle for capping individual emitters once they reach their maximum, shich I thought was 1,800 (9x2,000), but in a conversation yesterday you indicated they emit only over 8 cells, which would imply a maximum of 1,600.

**Comment by knucracker** [comment]
One problem I identified was that the amount being passed into AddCreeper was an integer type. For an emitter with a high configure value (say 100 thousand) that would wrap around a few times and end up on a negative number. I've fixed this for AddCreeper.  Note that conversion can still happen when an emitter is set high (even well shy of 16k). The reason is the emitter creeper and waves don't have time to move out of the way. I've confirmed that conversion doesn't happen from the AddCreeper (after my changes), but you'll still  see spots of conversion on very high output emitters because of wave and flow conversions.
