### ISSUE TITLE
[Bug] 4RPL units present on a map aren't unloaded until map exit

### ISSUE THREAD

**Issue by Alophox** [KnuckleCracker/CW4-bug-tracker#271]
**Describe the bug**
On exiting a completed map that used custom 4RPL units, the game took a really long time to unload all unused objects- there were above 1 million of them. I haven't seen this before on vanilla maps, so it's probably the 4RPL units causing the delay. Each unit produces several more objects far more frequently than bertha and thor, plus they're relatively cheap. The spawned projectiles don't appear to be cleaned up until exit.

**Additional context**
Here's the output log.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5574442/output_log.txt)
and here's the editor save(finalize and run through it until done, then exit and the game will be unresponsive until what is effectively garbage collection is finished).
[save.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5574452/save.zip)

**Comment by knucracker** [comment]
The issue seemed to come from the specifiedtargetindicators. Those guys were creating meshes to hold quads, but they were not being cleaned up properly when the targetindicator was destroyed (which happens when a new one is set). That in turn lead to a whole lot of little quad meshes over time.

So try the mission again in beta5 and see if it behaves better. If it still shows a memory issue, make a new issue and I'll take another look.
