### ISSUE TITLE
_UNKNOWN map appears in editor.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#274]
1. Open "The founders" mission (can be any mission with 4RPL)
2. Press shift+E
3. Open the Cpack manager.
4. Open the Thor cpack.
5. Exit to main menu, go to map editor.
6. there is a a broken _UNKNOWN map there.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5575943/output_log.txt)

**Comment by Alophox** [comment]
This occurs whenever *any* Cpack is opened up from the shift-e editing inside a non-editor map. The new folder doesn't include a save, which looks buggy on the editor screen(pure white preview).

**Comment by knucracker** [comment]
I've made it so the __UNKNOWN directory is hidden in the map list. I actually made it so that any directory that starts with __ (that is two underscores) will be hidden. So if you have projects and want to keep them, but don't want them in the list in the game, just stick two underscores on the front of the directory name.
