### ISSUE TITLE
[Bug] Shift clicking unit while holding its target indicator allows it to be placed anywhere

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#363]
Found by Pilihp64 on Discord

1. Place and build a unit e.g. cannon
2. Issue a move order anywhere
3. Click the newly placed target indicator
4. Shift-click the original unit - the indicator is still following the mouse
5. Place the bugged indicator anywhere, even in areas where it shouldn't be allowed

Far as I can tell, the behavior works correctly if in step 3 you select the unit itself rather than grab its target indicator - the unit becomes fully deselected then.

**Comment by knucracker** [comment]
Some time back I made it so clicking a selected unit will deselect the unit. That introduced this problem. Clicking on a move ghost will select the unit and the move ghost. Clicking on the unit (with shift held down) will then deselect the unit. The bug was that the move ghost was still selected at that point. So it was a decoupled move ghost moving around.
