### ISSUE TITLE
[BUG] Mission 13 - Archon - Dialogue Box will not close

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#364]
From Steam discussion forums: I verified that the save file attached here has this issue. 
[quick.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5645920/quick.zip)

I have UI scaling turned up a bit to make it easier to see. With this set, the confirm button for the second lore cache dialogue box is off screen and you cannot reach it. I turned down the UI scaling and I can see the button now but cannot click it. Reloading the game or mission does not work. Rift Jumping does nothing as well. If I quit, I do have a complete mission, but I cannot go back and finish all of the objectives without starting over.

**Comment by knucracker** [comment]
The issue with not being able to click the button to close it is fixed.  The issue with the dialog being tall, without lowering the aspect ratio isn't addressed.  It requires a really wide aspect ratio to get the problem, and at that aspect ratio UI scaling seems to be required for the rest of the UI as well (otherwise the left menu is off the screen in many cases). Since UI scaling is required at wide aspect ratios then that seems to also take care of the issue when the button is not visible.

**Comment by knucracker** [comment]
I also changed that text dialog in this mission to removed a couple of lines. That will buy a little more vertical real estate
