### ISSUE TITLE
[Bug] Glitchy graphics on virtual machine

### ISSUE THREAD

**Issue by TheRamenChef** [KnuckleCracker/CW4-bug-tracker#378]
It doesn't seem to be affecting anybody else, but I'm getting really glitchy graphics on every map that I play. As shown in the below screenshot, the terrain textures for much of the map is missing, though some of the shading is visible. Which parts of the map are missing changes when moving the camera or when the game is unpaused, but some terrain textures are more persistent than others. Units are mostly unaffected, though soylents aren't always drawn.

![Screenshot](https://user-images.githubusercontent.com/29645476/101259797-b7e19f80-36f0-11eb-8f24-938006abbeca.jpg)

I'm playing in a virtual machine (Parallels Desktop 16.1.1), could that have anything to do with it?

**Comment by Karsten75** [comment]
I am assuming you are running MacOS on an Apple computer, otherwise I'd suggest you  try running natively and see if the issues persist. 

From the Parallels  website (https://kb.parallels.com/122807) With my emphasis

"Parallels Desktop has no access to the Mac's device's physical graphics cards. Instead, Parallels Display Adapter driver (which is part of the Parallels Tools installation) interfaces with virtual hardware and provides 3D acceleration features. The actual acceleration is achieved by **_translating Direct X commands from the guest OS to the OpenGL API on the macOS side._**"

And that is most likely  your issue. OpenGL does not play nice with the game graphics

If it is not too late, I'd strongly suggest you refund the game until such a time as you are able to play it on a supported platform, or the game supports more platforms.

**Comment by Karsten75** [comment]
Closing
