### ISSUE TITLE
Ac drops from 50k to 20k after collecting it with a spayer

### ISSUE THREAD

**Issue by Vikiwifi** [KnuckleCracker/CW4-bug-tracker#394]
Help us help you. 

3. Screenshots help! 
  Screenshots are here
![image](https://user-images.githubusercontent.com/61553315/101285307-ba252600-37e4-11eb-8bed-b50e56baf4da.png)
'C:\Users\YOUR_USER\Documents\My Games\creeperworld4\screenshots\'

4. Describe the bug 
Ac tumbles on its self disappearing

**Additional context**
Uploaded a video of it happening
[https://youtu.be/TgHzAY8TqOc](url)

**Comment by Regallion** [comment]
AC higher than 2147 becomes creeper and you can actually see than in the screenshot. Slow your roll.

**Comment by knucracker** [comment]
A number of folks have been confused by this, so I've changed the collection field on the sprayer to a different pattern. It's more of a spiral. This has the effect of making the collection field less strong so that the volume of AC collected has difficulty reaching the overflow value in the center (the collected AC gets wider instead). Overflow can still occur with this new model, it is just less likely to do so by accident.
![image](https://user-images.githubusercontent.com/6733225/101288022-188cdd00-37c2-11eb-9076-428148faeeb9.png)
