### ISSUE TITLE
Ctrl-A input sometimes also registers as A

### ISSUE THREAD

**Issue by Squornshellous-Beta** [KnuckleCracker/CW4-bug-tracker#434]
When using ctrl-A (with default keybinds) to select all units of the selected types, the game sometimes, but not always, also moves the camera to the left. I have not noticed a clear pattern for when this does and does not occur, though it seems more common when only a single unit is selected than when multiple are.

**Comment by Karsten75** [comment]
Would love it if you would keep observing this and see if you can find more exact steps to recreate.

**Comment by Squornshellous-Beta** [comment]
Recreating it is quite easy: Simply go into any level and repeatedly press ctrl-A (or ctrl-any other directional button, or presumably any button with a clearly visible effect).

Having tested it further, it seems to happen only when the buttons are pressed within a relatively short window of one another, likely explaining my previous belief that it was less likely when multiple units are selected; I tended to try to repeat it when it happened, and so had ctrl held down from the previous time rather than releasing it to press again. Note that the issue is definitely not the keys being pressed in reverse order by mistake, as it still also registers as ctrl-A and selects all units of selected types.

Attached is a video of me demonstrating it, though for obvious reasons the keypresses are not directly visible.
[cw4.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5680596/cw4.zip)

**Comment by knucracker** [comment]
This is likely caused by releasing the ctrl key prior to releasing the 'a' key. As long as ctrl is held down, pressing 'a' will register as ctrl-a.  If after pressing ctrl-a, ctrl is released but 'a' remains down, that registers as 'a' being held down and will cause the map to move left.  If after pressing ctrl-a, 'a' is released before ctrl is released, there won't ever be a case where 'a' is being held down.

It's a side effect of looking at cases of 'key down' vs 'key pressed'. The map pan handler checks to see if the key is down (being held down). Most key handlers check to see if the key was 'pressed' (meaning it has to be released and pressed again before it registers).

There isn't a lot I can do about this unfortunately. It would involve a lot of complicated logic that could also interfere with other expected behaviors.   So the recommended course of action for players would be; ignore it, always release 'a' before releasing ctrl, or remap to some other key(s).
