### ISSUE TITLE
[Bug] Porters towers not accepting blueite or redon from porter delivery.

### ISSUE THREAD

**Issue by B33Mack** [KnuckleCracker/CW4-bug-tracker#439]
During the mission Shattered, I attempted to use porters to move redon and blueite to the different islands but found that the towers didn't pull from the delivered supplies. This occurred only for blueite and redon, while the liftic worked just fine.

 
 
 
 
![Blueite_Bug](https://user-images.githubusercontent.com/75822221/101858313-95071f00-3b26-11eb-8901-aa3e6a05f5ca.png)
![Redon_Bug](https://user-images.githubusercontent.com/75822221/101858320-989aa600-3b26-11eb-9187-43a754861100.png)

**Comment by Karsten75** [comment]
If, by "towers" you mean Sprayers and Missiles, these don't use Bluite and Redon respectively, but they use Anticreeper and Arg, which you get by sending the Bluite and Redon to the fatory for processing and then you can use porters to take the processed wares to the units. 

If this is not your issue, then please provide a screenshot you take with Shift-F11 so the entire map is included. Also include the save file where the issue is happening on.

**Comment by Karsten75** [comment]
Closing due to lack of feedback/additional documentation.
