### ISSUE TITLE
CW4 No sound

### ISSUE THREAD

**Issue by Morial65** [KnuckleCracker/CW4-bug-tracker#455]
I have launched the game and I had no sound. So, I uninstalled it and reinstalled it to different drives (I have a main and two other drives attached to my laptop) still no sound. I have restarted my computer as well still, no sound. So, I am at a loss.
[output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5683789/output_log.txt)

**Comment by knucracker** [comment]
The log file contains this message, which I have never seen:

FMOD failed to initialize. This may be because your sound card is
configured to give applications exclusive access, thus preventing Unity
from using this device. You can change this in Control Panel > Audio
Devices and Sound Themes > Playback Device > Properties > Options ... :
"Soundcard does not support the minimum features needed for this
soundsystem (16bit stereo output). " (59)

This is also one thread the seems related to the issue:
https://forum.unity.com/threads/fmod-failed-to-initialize.602845/

**Comment by Tashen8181** [comment]
[output_log for CW4.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5691899/output_log.for.CW4.txt)

I had sound when I first installed the game, then it went out about halfway through the campaign missions.  I had done nothing but campaign missions up until that point.  Now I have finished the campaign and I have no sound on any player map or campaign missions.  Also, if I go back to the early campaign missions, I no longer have sound.  

I am guessing if I uninstall and reinstall I will be able to get sounds back, but I wanted to get you an output file here before I did that in case you found something, or you can compare the before and after if that helps.

**Comment by Karsten75** [comment]
Please check if you did not accidentally mute the game. There is a mute button on the UI and the default key is "M"

![image](https://user-images.githubusercontent.com/22965021/102147608-a30fb500-3e30-11eb-9800-f9a9c32af548.png)

**Comment by Tashen8181** [comment]
That was it!  Thank you!
