### ISSUE TITLE
[Bug] Creeper not counted for creeper graph

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#469]
[what.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5696625/what.zip)
![image](https://user-images.githubusercontent.com/40322714/102230842-64483080-3efe-11eb-9792-11d6cbc89d3a.png)

The creeper on this map is not counted in creeper graph no matter what.

**Comment by MutexMorgan** [comment]
Perhaps you should consider making it play and then noticing no bug, it is because most likely the update of graph is in Update method in Unity's monobehavior which runs code every frame, I assume that Knucracker made a count machine that counts these frames and then fires code to update that GUI part.
If it works that means it is not a bug but rather an aspect of unity engine and implementation technique of that counter.
Although I don't think it require fix, as if I am correct, it would simply display as soon as you play the mission and the timer fires the code.

**Comment by Regallion** [comment]
You..COULD just download the attached map file and see that no, the creeper in this case does not go into a graph.
If you deposit some creeper elsewhere it will count, but absolutely not this batch.

**Comment by MutexMorgan** [comment]
It is because the creeper is on square that has wall unit on it, and only because of that.
I don't think creeper would enter squares with walls on it during natural game process, on usual wall it would shut it down quickly and it would count again.
But yeah, it is a bug.

**Comment by Regallion** [comment]
It can enter squares with walls on a natural game process, the only thing that is required for it to happen is a spore launcher set to random.
