### ISSUE TITLE
[Bug.Minor] Colonies sometimes shows default text

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#476]
Enter colonies. Quickly select any map.
Only works from fresh boot.

![image](https://user-images.githubusercontent.com/40322714/102264882-5064f480-3f27-11eb-9897-936494514873.png)

**Comment by knucracker** [comment]
The easiest way to reproduce this is to clear the thumbnail cache from disk. Then bring up the colonies and select a map before the thumbnail was downloaded. This was causing an exception. I fixed the exception, which allows the game to load the rest of the data properly. The image still shows white since the map was clicked before the download of the thumbnail completed, but click the map again will refresh the image. That's close enough for government work...

Note this could also be reproduced if you clicked a map within 1 frame after loading the colonies. I also changed it so the thumbnail cache doesn't have to wait a frame to load the thumbnails.
