### ISSUE TITLE
[Bug] null reference exception in log file. 

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#478]
[nullref output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5698659/nullref.output_log.txt)

From a Discord discussion. 

https://discord.com/channels/192420539204239361/776875809893253150/788506012268494878

**Comment by knucracker** [comment]
I nit sure if this has anything to do with the issue reported on discord. In any case, I have an additional check in place to prevent this possible exception.  It looks like the exception happens if the game is started and there an achievement needs to be granted that wasn't previously granted. It would happen on game start. If the player entered a mission and came back to the main menu, it wouldn't happen again and the achievements would be synced.
