### ISSUE TITLE
[Bug] Objectives incorrectly showing in Colonies

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#484]
So. I recently started remaking story maps into a harder version, and when I uploaded Farsite (Harder), the objectives were uncorrectly detected. The mission starts with a custom objective called --OFFLINE--, and it is later changed into a totem objective, which is the only one you can complete. However, the objective detected is the custom one.
As you can see on the screenshot, the only objective here is the never completed custom one. Note that I did beat the map in order to upload it.
![image](https://user-images.githubusercontent.com/76114055/102368499-3248d400-3fbb-11eb-9f29-338066e6e75d.png)

**Comment by knucracker** [comment]
I've made a change on the server so that objectives in the map are merged with any objectives that are present in the play log database at the time of the map upload. The superset of these objectives becomes the objectives on the map. If map 165 were uploaded now, it would have custom and totem objectives. Now the custom objective isn't really one, but this solution is a step in the right direction since it would show the totem objective.

For map 165 specifically, I have manually changed it in the DB to only show the totem objective.
