### ISSUE TITLE
[Bug] No-pause GameMessages from InfoCaches cannot be dismissed [1.0.1 Beta]

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#501]
[11.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5715720/11.zip)
![image](https://user-images.githubusercontent.com/40322714/102616618-e461d680-4148-11eb-8c3a-6995f934f6be.png)

After collection the message remains indefinitely and depending on length can be detrimental to gameplay.

**Comment by knucracker** [comment]
I had it that way because I thought the message might be left up for some time, then closed by 4rpl. But that's such a rare thing. And if desired, then it can be totally done in 4rpl (with no message specified by the infocache). So I've changed it to show the Dismiss button on an infocache game message if there is a message and there is no button present.
