### ISSUE TITLE
[Bug] Mark V setting mysteriously reset

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#504]
Open mark 5
Paste in PRAYSE THE FOUNDERS#1444. Hit "Apply"
For 1 frame, the settings will be correct, but they will immediately reset to 2221

**Comment by Karsten75** [comment]
this is not about "paste", The issue arise then the player enters data into the input fielld and adds the #-values to the input field. Then to have it applied, then "apply" button has to be pressed.  This does not fully take effect and the values revert to other values after a brief period

**Comment by knucracker** [comment]
The text field was applying anytime there was a change. It would parse what was in the text field and if there was a #xxxx on the end if would extract that an put that into the toggle controls. Manually pasting  PRAYSE THE FOUNDERS#1444 and then hitting apply would do just that. It would extract out the PRAYSE THE FOUNDERS part and then put that back into the text field. It would extract the 1444 part and apply it to the toggles. Putting 'PRAYSE THE FOUNDER' in the text field would cause another update which would parse again. This time, there was no #xxxx on the end (it had been removed). That in turn would case default toggle values to be applied.

I have changed it so that the toggles are not altered when changing the keywords (via paste or any other mechanism). The toggles should only be changed when they are changed manually or there is a #xxxx on the end of the seed words.
