### ISSUE TITLE
[Bug.Minor] Removing a custom mesh from a CPACK removes all meshes from all units in the same CPACK

### ISSUE THREAD

**Issue by e-d-u-r-a-n** [KnuckleCracker/CW4-bug-tracker#542]
When removing a custom mesh from a CPACK, all units lose their stock meshes on every single object. Custom meshes stay in place.

Before / after screenshots:
![before](https://user-images.githubusercontent.com/75800362/102989203-81d85400-4515-11eb-96a6-ef17152edfd0.jpg)
![after](https://user-images.githubusercontent.com/75800362/102989208-83a21780-4515-11eb-85aa-9fc75e6a8c97.jpg)

It is not just a display bug in the CPACK manager. Updated or newly placed unit instances are invisible.

**Comment by knucracker** [comment]
In the beginning, there were only custom meshes. I later added the stock meshes. But, I never updated the old "clean" code that runs when removing a mesh. So upon removal of a mesh each object was attempting to clean itself up by checking to see if the mesh it held was still present. It was only looking at custom meshes, so it was removing the stock mesh. I've updated so that the cleanup code knows it is holding a stock mesh and won't remove it when a custom mesh is deleted.
