### ISSUE TITLE
[Bug.Minor] Skimmer factory doors do not respect pause.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#551]
1. Place a skimmer factory on the level.
2. Once the doors start opening or closing, pause.
3. Expected: doors freeze
4. Reality: doors continue the current animation until it finishes.

**Comment by Karsten75** [comment]
ERN crystals don't stop rotating during a game pause either. and is far more pervasive in the game than a trivially small  animation. 

For this to be a bug, it has to deviate from a specification. Since it doesn't, and  the door animation is really not germane to any function of the game.  I'm going to close this.

**Comment by grabz-dev** [comment]
Do skimmers have to wait on the doors to open? If yes, I'd say this is valid.

I know that for spore towers the animation matters for when it spawns an egg i.e. if you have a nullifier on a spore tower and want its spore timer to count but you don't want an egg to spawn, you want to make sure the tower is nullified while the mouth is open and not nullified while the mouth is closed.
