### ISSUE TITLE
[Suggestion] Explain "void height" to the player in a tutorial.

### ISSUE THREAD

**Issue by etmoonshade** [KnuckleCracker/CW4-bug-tracker#572]
**Is your feature request related to a problem? Please describe.**
Note that this is NOT a request to change the mechanics.

Void height is unexplained in-game, and the visual representation of void doesn't match the mechanics of it.

As far as the player can deduce from the visuals, the void is 0 height:
- https://media.discordapp.net/attachments/368747848046739456/793264940927549471/unknown.png?width=869&height=624
Note that the cannon's fire range is blocked by the cliffs - it can't depress its trajectory far enough to hit the void except once it's about 6 units out, which implies that the void is indeed at 0 height.
- Blobs crawl along the void at 0 height, and take time to climb up cliffs from 0 height.
- Creeper landing in the void appears to pool at 0 height - at least until it hits a cliff.
- ERNs travelling over void will follow the terrain contours as if void is 0 height.
-- Oddly, units travelling over void do NOT appear to follow terrain contours when going over void based on my test. Go figure.

**Describe the solution you'd like**
The most accessible option with the least amount of work is probably a tutorial entry somewhere in the story, most likely something from Sarge observing that creeper is floating in from the void.

Mission 7: We Were Never Alone seems to be the best place to put it - it's the first mission with both void and spores, and based on a quick test, the following scenario actually happened to me:

In the northeast and southeast corners, there are two islands. Scripting at least one of the first volley of spores to hit *near* the island could trigger a tutorial message.

**Describe alternatives you've considered**
The most extreme option, obviously, is to change mechanics to match - no firing cannons/snipers into void/full coverage of cannons/snipers into void, make void height *actually* 0, etc.
Needless to say, this ain't happening.

Second most extreme option is to somehow change the visuals - blobs float their way over void instead of shimmying along the ground, creeper flows differently through void, etc.
Again, almost certainly not happening - this would pretty much necessitate changing the mechanics as well, or you'd be back to mechanics not matching visuals.

Third option, and obviously easier, is to add documentation somewhere - either the wiki or the in-game help. The in-game help is more accessible, but it looks like it might require a new section. The wiki page linked to from the "game interface" help option *may* be a sensible place to put this, but it's focused on the interface rather than the mechanics. I don't think this is as accessible as a full tutorial entry though - there are enough of them to cover other mechanics.

**Additional context**
As a long-time but casual player, the "void height" mechanic both came as a surprise to me and doesn't appear to match the visual feedback I get. As far as I can tell, this mechanic is not explained anywhere in-game, may be mentioned on the wiki (though I haven't found it,) and has been discussed rather excessively on Discord.

One interesting observation from the Discord conversation I had is that this worked the same way in CW3, but I either didn't notice it or didn't remember it (it's been 5+ years since I played.) It seems like two things were at play here - the 2D interface didn't make height differences seem as extreme, and more relevantly, it apparently didn't happen *nearly* as often.

I think the fix in #559 only makes sense if you know the mechanic exists in the first place - otherwise, it just looks like a buggy indicator. It makes sense once you know how the void actually works, of course, but again - that's knowledge I didn't even have until I joined the Discord and read the part of the chat where the decision to make that change was made.

The visuals not matching the mechanics is downright *confusing*, and this is really the root of my complaint/suggestion here. I know it's way too late to do anything about the visuals unless you can miraculously contrive a way to fix them in a way that reflects the mechanics, but please keep it in mind for the next game.

**Comment by knucracker** [comment]
A line in the tutorial would not hurt, but that would only help a small percentage of players. People don't read (or listen). If I've learned anything, I've learned that :)

In short, the creeper is drawn to land. Creeper that finds itself in space (or on the planet) is drawn up onto the land. Void height, etc. is how it is talked about on discord and the forums. It is certainly implemented that way, but from a casual player's perspective they just observe that creeper in space will flow up onto land. In extreme cases (which most casual player's don't encounter), the creeper will flow back into space.  The actual observation that creeper flows up onto land seems to be to most salient way players learn that it will do that.

What would be good, perhaps, is confirmation that it is supposed to work that way in the documentation. Either in the built in info panel or on the wiki that the info panel links to. After making the observation, some player's want either to know if that is 'correct' or they want some lore about it.

**Comment by etmoonshade** [comment]
Based on some casual experimentation in other venues, it's about 10-15% of people who don't read. It's just that those 15% are the ones who are typically the most annoying to you (why the f don't you people READ ARRGH,) so you REALLY notice them. :D

For what it's worth, I didn't actually *observe* climbing creeper for quite a while. It was always me paying attention to a different portion of the map, and suddenly I have stuff blowing up near a cliff somewhere and just a little puddle of creeper. I always chalked it up to a random spore that got through my defenses or something, because let's be honest - I am not a good player. :V  The reality, of course, is probably that it "snuck under" instead.

I guess I technically observed it any time there was mesh over void too, but again, that mechanic explicitly draws stuff along it (from a player's perspective - I actually had the mechanics explained to me but I'm trying to stay in the mindset of a somewhat new and uneducated player) so it made sense that it was able to climb those walls.

I also observed it in the level where you get the porter, on the small islands between the big ones, but it's a lot more visually logical to see it flop/slosh from height 0 to 1 than height 0 to 10.

The problem in my eyes is that all the observations I made were attributed to other known mechanics. <_<

Finally, documentation is always a good and (relatively) easy answer - the tutorial line is just to put it in the player's face. The tutorial text is right there for the player, whereas I think most people read through helpfiles for a particular subject - not to just browse through.

Thanks for the reply!

**Comment by keybounce** [comment]
Adding a comment here; I know it's not going to change in 4, but I do want you to understand how annoying this is.

> As a long-time but casual player, the "void height" mechanic both came as a surprise to me and doesn't appear to match the visual feedback I get. As far as I can tell, this mechanic is not explained anywhere in-game, may be mentioned on the wiki (though I haven't found it,) and has been discussed rather excessively on Discord.

I'm not long time. I'm pretty new. But this "attack from the zero" -- https://steamcommunity.com/app/848480/discussions/0/6811212461220638239/ -- it's not hard to encounter and really makes no sense.

Absolutely this needs a callout in the tutorial missions.
Absolutely the next game would need better graphics (and ... I have no idea how. Magically floating around the middle of the ground height, with a gap above and below???).

> . In extreme cases (which most casual player's don't encounter), the creeper will flow back into space.

Huh. I'm the oddball then -- I have noticed it, or at least, land creeper still connected to *thin* space creeper has the potential to retreat out from land, and space creeper will eventually fade away from land if thin enough.

> Third option, and obviously easier, is to add documentation somewhere - either the wiki or the in-game help. 

Now, this is good. Having recently learned that the wiki is "bare bones plus player additions", I'm adding what I learn about the game (there's a lot lacking. sigh). But I don't know what to say, because I don't know the mechanics properly. I know that I don't know what to document.

> and has been discussed rather excessively on Discord.

**Discord is not a knowledge repository! **

Google cannot search Discord
There is no good search function in Discord.
While any given channel has useful information, there is so much non-useful chat that it will be lost.

Forums (both CK and steam) are knowledge. Search engines find them. They're probably in LLM training. (Hmm ... yes -- below are two of them.) But the point is, information only found on discord is only seen by a small percentage of players who use it, and then only a small percentage of that. And it probably comes up again and again, under different names, right? People can't find it, and can't find an explanation -- not even an in universe one.

FWIW, I ran into this in CW3, and attributed it to "Game mechanic rules". I see a very clear "Way way down there, don't worry about it when building high up on a cliff", and ... it's *worse* than the mesh cliff climb. At least that has both A), a visual (the mesh), B), an in-game concept (something has created this structure, and we know that creeper is made by some life hating entity), and C) a way to deal with it (TERP the mesh ground down to height 1 -- include one space of normal ground just outside the mesh itself.) But "A tall cliff next to the void is a danger and a threat to you"?

If the creeper can come from void/space down onto land, why does it only arrive at the land edge, and why not anywhere (if it's really coming from space)? Why doesn't it float through the space above the land anyways. Why is putting a ring of height 1 all around my island expected to save me from a space attack?

I feel like this should be some sort of water attack. Hmm ...
"This creeper is coming at us from under the water. We can't drain the oceans, and cannons cannot reliably hit it. Mortars at least can. Oddly, once it does hit the beach, it seems able to raise up no matter how high the cliff face is -- whoever created this must have understood science in a way we don't yet."

Maybe instead of an outer space campaign, we need some sort of "defend the planet" campaign? :-)


[quote]
You
Tell me about void height in the game creeper world 4
Meta AI
In Creeper World 4, void height refers to the distance between the terrain surface and the void (the empty space below the map). It's a crucial concept in the game, as it affects the behavior of creepers and other entities.
Void height is measured in units of distance, and it can vary depending on the terrain generation settings and the specific map being played. A higher void height means that there is more space between the terrain surface and the void, which can affect the movement and spread of creepers.
Players can use various strategies to manipulate void height to their advantage, such as creating barriers or channels to control creeper flow. Understanding void height is essential for building effective defenses and managing creeper spread in Creeper World 4.
Would you like more information on Creeper World 4 strategies or gameplay mechanics?
[/quote]
A per-map setting?? Not just a constant behavior???

Gemma's version (https://web.gemma.ai/conversations/fe2a0f3a-ae1a-4e15-8a2e-594bdc725535)
[quote]In "Creeper World 4," the concept of void height refers to the level at which the terrain ceases to exist, essentially creating a bottomless area on the map. This feature impacts gameplay significantly:

1. Strategic Challenges: Units or structures placed too close to the void can be at risk. The void can act as a barrier or a strategic point, depending on the map and the player's approach.
2. Map Dynamics: Certain maps in "Creeper World 4" utilize void heights to introduce unique challenges or to shape the flow of the game, influencing where and how players can build or defend.
3. Visual Impact: The void areas also serve a visual purpose, adding depth and complexity to the game's aesthetics.

Understanding and utilizing the void height effectively can be crucial for mastering the game's more challenging levels. Would you like tips on how to manage void heights effectively or details on specific levels that feature this element?
[/quote]

**Comment by Karsten75** [comment]
If you want a reasonable discussion, join us on Discord and I'll try and answer some of your questions. But this word soup - it's just too much for me. Sorry.
