### ISSUE TITLE
[Bug] Random Unity crashes during story missions

### ISSUE THREAD

**Issue by AidanCodes** [KnuckleCracker/CW4-bug-tracker#577]
**General Description:**
- The game may briefly freeze and then crash at any time during any story mission (I have tried 1-8 thus far).
- The game will crash to the Windows desktop and cause a black screen on all connected monitors (perhaps graphics driver related?).
- Audio continues to play but the game cannot be brought back to the foreground successfully.
- The Unity crash handler is activated but also fails to take the foreground.
- The game's cursor can be made visible by Alt-Tabbing.
- The game will only exit through task manager.

**Logs:** 
- [output_log.txt](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5756203/output_log.txt)
- [Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5756204/Player.log)
- [Player-prev.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5756205/Player-prev.log)

**Steps to recreate:**
1. Run game via Steam and load any story mission.
2. Play until freeze and crash (usually < 15 minutes)

**Screenshot** (Post crash):
![CaptureCW](https://user-images.githubusercontent.com/7085975/103390015-2a6f5080-4ae0-11eb-9dfa-eace605dade0.JPG)

**Additional context:**
- Crashes occur on beta 1.0 and 1.1.1 builds
- This issue persists across reboots and appears random to trigger (without a thorough understanding of the log format and Unity).
- [See steam discussion here](https://steamcommunity.com/app/848480/discussions/0/2998799976104338464/)
- Issue originally posted by Steam user Vahnkiljoy on 12/27/2020

**Game/System Info:**

Game Version = 1.1.1
Unity Version = 2019.4.16f1
Command Line = ["D:\Steam\steamapps\common\Creeper World 4\CW4.exe"]
Time Since Game Start = [65.58006]
----------------------------------------------------------------------------------------------
OS = Windows 10  (10.0.0) 64bit
System Memory = 12242
MP4 Supported = true
----------------------------------------------------------------------------------------------
Processor Type = Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Processor Count = 8
Processor Frequency = 3392
----------------------------------------------------------------------------------------------
Graphic Device Name = NVIDIA GeForce GTX 1060 6GB
Graphic Device Version = Direct3D 11.0 [level 11.1]
Graphic Memory Size = 6052
Graphic Shader Level = 50
----------------------------------------------------------------------------------------------
Game Dimensions = 1920 x 1080
Resolution = 1920 x 1080 @ 60Hz
Displays = Display (0) Sys=[1920 x 1080] Rend=[1920 x 1080] ACTIVE  Display (1) Sys=[1680 x 1050] Rend=[1680 x 1050] INACTIVE  
DPI = 96
UI Scale = 1
Target Frame Rate = 60
----------------------------------------------------------------------------------------------
Settings: AA = 1
Settings: FPS = 1
Settings: SHADOWS = True
Settings: BLOOM = True
Settings: TERRAIN = True
----------------------------------------------------------------------------------------------
Device Type = Desktop
Language = English
Supports Audio = True
----------------------------------------------------------------------------------------------
Max Texture Size = 16384
Max Cubemap Texture Size = 16384
Support Shadow = True
NPOT Support = Full
Support Render TargetCount = 8
Support 3D Texture = True
Support Compute Shader = True
Graphics Multithreaded = False
Supported Render Target Count = 8
Supports 2D Array Textures = True
Supports 32 bit Index Buffer = True
Supports Image effects = True
Supports GPU Draw Call Instancing = True
Uses Reversed Z Buffer = True
Supports Sparse Textures = True
Quality Level = 3
Gen = True [Can Confirm: False]

**Comment by AidanCodes** [comment]
I was also able to get the game to crash without Unity crash handler being activated. The result is the same.

**Comment by knucracker** [comment]
The error in the log file is:
"d3d11: failed to create buffer (target 0x5 mode 0 size 144) [0x887A0005]"

That's a problem that starts in the driver (from a software perspective) and then moves up. It can originate with hardware, other software, interaction with other software, driver, etc.

The usual recommended approach is to start conservatively and move outward. So I'd start with:
- A full reboot (you have already done this, but putting it here since it's always the first step and it work more than half of the time).
- Disabling the steam overlay. Right click the game in steam and go to properties. Disable the steam overlay from there.
- Ensure other software that might interface with the GPU isn't running. Things like game recording software can be a culprit. Other software like Razor synapse has also been historically associated with a number of game crashes.
- Reinstall the game.
- Run the game in different modes.  In a window, in a smaller window, full screen, fullscreen exclusive. Do any of those work? That can help narrow down the problem if some work and some don't.
- If you are on a multi monitor system try turning the other monitors on or off or running the game on a different monitor. Multi monitor support and some versions of GPU drivers have a higher crash rate.
- Try using a different game graphics driver. The game is compiled with support for Vulkan as well as DirectX11. In steam you can specify a command line argument. Right click the game in steam and go to properties. From there specify the is 'Launch Option':  "-force-vulkan" (without the quotes).  There may be a few graphical glitches in the game when running under the Vulkan driver. But if it works under Vulkan but crashes under directX11, that can shed some light.
- New builds of the game (over time) might change unity versions and that could change when and how the crash occurs. So if there is a beta build of the game available on steam, switch to it to see if that affects the problem.

If none of that works, the problem lies outside the reach of the game.  Googling the error in the log shows a range of games on a range of machines that have experienced this problem. The solutions vary, but are outside the scope I can recommend as they involve system changes and other lower level things.

Here is one result I found from googling: " d3d11: failed to create buffer (target 0x5 mode 0 size 144) [0x887A0005] "
https://forum.airportceo.com/t/solved-game-freezes-then-ctd/15363

**Comment by knucracker** [comment]
I've just updated the "beta" branch of the game on steam to be built with unity 2019.4.17f1 (1.1.1 of CW4 was built with 2019.4.16f1). 2019.4.17f1 is the latest (at the time of this post) LTS version of unity.  If the crashes resist any efforts you could try switching to this version and see if it makes any difference.

At the time of this post the beta branch is version Creeper World 1.1.1a and is built with Unity 2019.4.17f1

**Comment by knucracker** [comment]
Also note that I have create a github discussion for crashes. I would have moved this issue to a discussion, but Github has temporarily removed that ability while they fix bugs with it. In the mean time, head over to the discussion for more info and to post any followups.  I will close this issue.  Here is the discussion:
https://github.com/KnuckleCracker/CW4-bug-tracker/discussions/579
