### ISSUE TITLE
[4RPL] SetUnitMaxAmmo affects unit type instead of unit if ammo ware is not energy

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#609]
1. Create a map
2. Create a unit
3. Set it's ammo ware to be anything BUT energy.
3. Give it the following script: `1 15 SetUnitMaxAmmo`
4. Create 3 instances of this unit, such that at least one instance has an ID of 1
Expected: Instance with an ID of 1 will have max ammo of 15, other instances have max ammo of whatever was set in editor, default 0
Reality: all instances have max ammo of 15

If the ammo ware is energy, this behaves as expected.

**Comment by knucracker** [comment]
Fixed in 1.1.2c.  This was tricky and a little lower level than I would prefer. The AMMO_WARES and BUILD_AMMO were dictionaries. When a unit is created it was copying a reference to these dictionaries. That's why changing one would change all. I have changed UnitManager to make a copy of these two settings dictionaries when a unit instance is created.
