### ISSUE TITLE
[4RPL] Creeper can cover object text

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#611]
![image](https://user-images.githubusercontent.com/40322714/104127145-82744580-5371-11eb-905f-e53ff7d76332.png)
![image](https://user-images.githubusercontent.com/40322714/104127170-9a4bc980-5371-11eb-9f16-4bef438e309e.png)

Script for unit:
`			Self "Text" "Thanks for rescuing me from the evil creeps!" SetObjText 
			Self "Text" 50.0 255.0 div 220.0 255.0 div 50.0 255.0 div 255.0 255.0 div V4 SetObjTextColor 
			self "Text" 15 SetObjTextFontSize`

**Comment by knucracker** [comment]
I've changed the unit obj text to have an overlay shader. This means it will appear in front of other things, even if it is behind them (this includes terrain). This solves the transparency z sorting problem problem.  However, in some cases it might look strange.  I think in the case of the story, it will all look fine since the text is always 'high' up. 

Changed in 1.1.2c
