### ISSUE TITLE
[Bug.Minor] "Enemy" unit tag overwrites "Can ERN" effects in unit editor.

### ISSUE THREAD

**Issue by WithersChat** [KnuckleCracker/CW4-bug-tracker#655]
The "Enemy" tag has a lot of effects in the CMod editor. An enemy unit is:
-Unit: ON/OFF force-hidden
-Armed :ON/OFF force-hidden
-Supply: ON/OFF force-hidden
**-ERN :NONE/(WANT/HELD) force-hidden**
-Enemy "launcher" target
For most of them, it makes sense. but as "Can ERN" is already a separate tag, it would make more sense if it was actually independent from the "Enemy" tag.
(BTW maybe a way to remove a unit from blob/spore/skimmer/airsac target list? If it's not doable without altering the other missions, then np. However that ERN issue feels weird)

**Comment by Regallion** [comment]
A summary of discord discussion.

Currently, the "Enemy" checkbox, broadly does 2 things:

1. It causes most of the Player-controlled standard UI to vanish (The 3 control buttons+ERN button even if otherwise enabled)
2. It makes the unit an invalid target for blobs and spores (they will not target it)

Now, on the surface, those 2 things do not seem to be directly correlated.

This is unfortunate, because it means there is no way to make a friendly unit that is not a valid blob/spore target, without also making it not occupy terrain which can be undesirable. (and does not prevent spores from targeting it)
In reverse, that also means it's impossible to make an "Enemy" that the player can control, with default controls. An example was made of a PAC map entity, which is a custom spawner of blobs that only works when ERNed (to limit the amount the player can deploy), which as-is became the target of itself.

A compromise would be to add a way to separate "Cannot be targeted by" flag(s) and the "Disable normal UI" flag on a unit, regardless of whether or not the unit is an enemy and leave the "Enemy" tag behavior as-is (for backwards compatibility). The flags can be 4RPL-only.

**Comment by WithersChat** [comment]
The "Enemy" tag ALSO prevents the unit from being player destroyable, even if the "Player can destroy" flag is active.

**Comment by knucracker** [comment]
1.2.4 made a change so that the ERN:Want button is no longer tied to the enemy status.
