### ISSUE TITLE
[4RPL Addition] Allow defining of legal movement/building cells for unit/unit type.

### ISSUE THREAD

**Issue by Regallion** [KnuckleCracker/CW4-bug-tracker#667]
Logging so that it's not lost.

Right now, custom units are allowed to have 2 special conditions on their building/moving:
1. Any cell within the footprint must contain resource terrain
2. No cell within the footprint is allowed to contain contaminant

Unit movement and placing algorithm correctly handles cases where multiple units with disparate conditions are ordered to move together.

Allow extending that definition via 4RPL.

**Comment by knucracker** [comment]
Added Get/SetCellOccupiedCount. These may be useful for this purpose.

**Comment by Regallion** [comment]
Partially, but since units don't operate while paused, ever, i would still need to offload the cell-checking logic to a global script. Which is significantly less than ideal. 
(If a unit could at least know it was selected while paused it could then send a message to the global script but even that is hacky)

**Comment by knucracker** [comment]
Note sure if the following gets closer, but see below for additions:

I've added a :_Selected callback that can be used while a unit is paused.  It is in the 4rpl doc now. https://knucklecracker.com/wiki/doku.php?id=4rpl:commands:func_selected

It is also possible for units to operate while paused. There are some things to note, though.
The pattern is:
- Create a global script and set it to either Pre or Post execution (or create two scripts, one for each). Set it to run when paused.
- In the global script call SendMsg("RunPaused" 0)
- In any unit that you want to execute while paused, add a :Awake function with this in it: RegisterForMsg("RunPaused" "MyCall")
- In that same unit add a function named ":MyCall" (or whatever name you registered in RegisterForMsg).

This works because :Awake runs when a unit is first created (even if the game is paused). In Awake you are registering for callbacks that will be made by the global script that runs while paused.

Of note: 
- Global scripts run either before all unit scripts or after (post) all units scripts.
- When the game is unpaused, the unit's normal script body  (if any) will execute on a given frame in addition to the "MyCall" callback.
