### ISSUE TITLE
[4RPL] Sound loops don't work

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#740]
**Is your feature request related to a problem? Please describe.**
The PlaySoundLoop function doesn't play any sound when used. I modified the sound player tool from the wiki to run the loop sounds (on a valid unit) to check them all, and none of them worked. No errors were displayed in the tracelog.

[Player.log](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5992707/Player.log)

**Comment by knucracker** [comment]
There was an issue with the names. If you remove the "soundloop_" part of the name they would play. The game was automatically adding the "soundloop_" prefix to the sound presented via 4rpl. I have changed it so that the game will try to play the sound presented. If it can't, it will then try it again after it adds "soundloop_"
