### ISSUE TITLE
[Bug] Singularity transforms anticreep to creep above a level of 2000.

### ISSUE THREAD

**Issue by Dikkevis** [KnuckleCracker/CW4-bug-tracker#748]
When using a singularity to raise anticreep above a level of 2000, it transforms the anticreep into creep, destroying whatever building is underneath.

**Comment by WithersChat** [comment]
This is not a bug, it's intended. The max creeper level is 2147.483647. If it goes higher, it turns into AntiCreeper. The same way, AntiCreeper turns to Creeper. That's what happened to you. The Creeper flow works like that since Creeper World 2. Many people are surprised to see this the first time they do (I myself was surprised to see it happen in CW2).
