### ISSUE TITLE
[Bug] Nullifier Line of Sight Ignored

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#779]
A nullifier only seems to check if 1 enemy is in range and has Line of Sight. However, upon completion all enemies in range are nullified, regardless of Line of Sight:

![image](https://user-images.githubusercontent.com/68601223/109708018-24a6f180-7b9b-11eb-85eb-bd424c35fd55.png)

**Comment by knucracker** [comment]
Some time before release I changed nullifiers to not require LOS. The idea being they can shoot through things with their energy beams. So nullifiers weren't enforcing LOS, but the placement ghosts were.  I have changed it so that placement ghosts don't require LOS.  This makes them consistent with the intended nullifier behavior.
