### ISSUE TITLE
Discard Tags or change the system

### ISSUE THREAD

**Issue by BilboGCL** [KnuckleCracker/CW4-bug-tracker#788]
Tags are often used to say something negative about the map in complete anonymity, not even a forum name is needed to say things like "BADMAP", "TOOLONG", "TOOBIG", "BORING", not talking about the profanities - this discourages mapmakers as well as players. Every now and then one complains on the forum (like the 1st comment in https://knucklecracker.com/forums/index.php?topic=36906 )
So, either let us only chose from a curated list or combine new tags with a public name. The way it is now, it sadly doesn't work in this world

**Comment by Regallion** [comment]
Arguably non-profantiy tags can still be accurate. like, if i tag a map TOO LONG, because it takes 15 hours to complete with no satisfying payoff, i'm not wrong and it's fair for me to warn people.

**Comment by knucracker** [comment]
After some thought, I have changed it so that tags continue to exist and can be filtered on, etc.  They can even still be added by players (in addition to added at map upload time).  The difference is that tags added by players do not automatically show up. It will take multiple instances from different players of the same tag before new tags show up.  So in summary:
1: Tags added at map upload time show up on the map.
2: Tags can be added by players, but they only show up once multiple different players add the same tag.
3: Tags can still be voted up or down, or out of existence.

This preserves most of the system, and I wasn't interesting in rocking the boat too much.  It hopefully also  helps cut down on spam tags while still preserving the ability for new tags to appear on maps in the future.

Note, the threshold for becoming a visible tag is something I can change on the server at any point.
