### ISSUE TITLE
[4RPL Addition] Allow interaction with factory resources

### ISSUE THREAD

**Issue by qople** [KnuckleCracker/CW4-bug-tracker#790]
**Is your feature request related to a problem? Please describe.**
There is currently no way to see what resources are stored in the factory, or to change them directly. 

**Describe the solution you'd like**
Adding the factory to GetUnitSettings/SetUnitSettings would probably be the simplest way to allow this.

**Describe alternatives you've considered**
A pair of Get/SetResourceStore commands would also work.

**Additional context**
I'm making an AI that controls player units, and want to let it place micro rifts, sprayers, etc. while taking the required resources into account.

**Comment by Regallion** [comment]
#600

**Comment by knucracker** [comment]
This was covered under #600 as regallion pointed out... so I'll close this one.  That said, I'll take a look. I can probably add the apis for getting and setting the wares. Internally there is already a way to remove wares.  For multiple factories, that's a bit tricky. It will probably land however the loop works out since I don't officially support multiple factories.
