### ISSUE TITLE
[Performance] Planes flying over map bounds impact performance heavily

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#798]
Planes flying over map bounds may impact performance heavily. I saw the UPS drop from 120 to ~60 from a set of planes flying over the map bounds on a small map.

I took a set of planes and have them fly around a point on the center of the map, all is fine, 120 ups. However, when ordering these planes to circle or formation bomb the corners of the map I found that the UPS is impacted heavily, to even 60 ups, which means the performance of the game as a whole has decreased by over 50%!

For the following assumed cause it is important to note that 1 corner of the map was unaffected by this performance issue. A guessed cause is that the axis system is at one of the corners of the map, this causes the planes to cross into negative coordinates on 3 of the corners of the map leading to the super slow/heavy calculations.

**Comment by PRG-YouTube** [comment]
To demonstrate the massive impact on the performance watch the UPS here: https://youtu.be/2gGN2zIxs-8

**Comment by knucracker** [comment]
The bombers were doing terrain collision checks. Those checks used a dda algorithm that didn't like negative coordinates.  The only reason the game didn't totally hang is because I have a safety check that prevents the loops from iterating more than 1000 times.  So each bomber was was checking the same 0,0 cell 1000 times, etc.  I have changed it to abort the checks if the checks go outside the map bounds.
