### ISSUE TITLE
[Suggestion][Performance] Improve unit movement performance by remaining disconnected during flight

### ISSUE THREAD

**Issue by PRG-YouTube** [KnuckleCracker/CW4-bug-tracker#803]
We were discussing on discord why unit movement is heavy, which might be because the moving units are disconnecting, looking for the network, and reconnecting on every update while moving. Based on speculations and having no insight on the actual internal mechanics some improvement might be possible.

To improve the performance, and assuming packet passthrough capabilities are/remain off, it might be possible for a moving unit to check whether the ammo is full and if so from that point just remain disconnected during moving. The connections would need to be enabled again at the final descend to allow the user to see those connections being made.

This is applicable to most movable units that are a packet sink only (non source) as the only packets that should come are the actual ammo, though special cases like the air ship must be excluded of course.

Thoughts?

**Comment by knucracker** [comment]
Well... lets give it a try.  I have implemented it so that it only applies to standard moving units (units that takeoff move and land according to the built in movement system). The tricky part if knowing when a unit needs packet of energy or a ware packet. Units by default stop asking when enough packets are enroute. They also stop asking during their packet request rate cool down.

I've implemented the same code used to request packets but with a few small tweaks (ignore any packets in enroute already, for one). That should allow units to perfectly simulate whether they need, or would need, a packet or a ware packet.  I've placed this check in the takeoff, movement, and landing phases for a unit.  So now when a unit takes off it terminates it's connections if it doesn't need the connection. It will only reestablish the connections if it needs a packet or if it has landed.

This doesn't affect the airship since the airship doesn't use the built in unit movement. It for sure affects cannons, mortars, sprayers, etc., and any custom unit that uses normal unit movement.

For performance I tested with around 100 cannons and it does make a notable difference as the units are moving.  I also play tested on a chronom mission and didn't notice any ill game play effects.  If you know of any custom units that might be a problem test 1.47 or later and let me know if you observe a problem.
