### ISSUE TITLE
[Bug] Pre-placed ERN portals get free upgrades.

### ISSUE THREAD

**Issue by Durikkan** [KnuckleCracker/CW4-bug-tracker#812]
If you make a map with a pre-placed ERN portal, finalize it, and then play the map, the ERN portal assumes it has ERNs installed for all types, despite not displaying that.  I.e. you'll gradually get more income from resources, etc.   This works for both prebuilt and blueprints, though the blueprint ones don't start increasing their bonus until they've finished being built.  

If you add a ERN for the type, it has no effect, but removing it restores the ERN portal to the correct state where no installed ERN = no bonus.  

Here's a screenshot with the bonus partially active, showing the increased energy up top, and the weapon range increased by a square with no ERNs installed.  

![ernPortal](https://user-images.githubusercontent.com/75511563/111225679-19e25880-85ae-11eb-9c5f-00e7ae1ed23a.jpg)

**Comment by Durikkan** [comment]
Worth noting that this only happens playing the finalized version, if you play in the editor it behaves normally (i.e. no free bonuses).  This bonus does happen to maps uploaded the colonies though.

**Comment by PRG-YouTube** [comment]
Confirmed on v1.4.7.

This might be an issue as a creator might be set a time to finish an otherwise impossible map

**Comment by knucracker** [comment]
The "reset" on the ern portal was resetting the dockTime to 0 rather than -1.  The dockTime is the frame an ERN docks with the ern portal. It is used to measure how long the ern has been docked. Since it was resetting to 0, that made the ern portal think there was a docked ern in every slot.  The ern portal reset gets called during finalized, hence the problem only after finalizing.
