### ISSUE TITLE
Rift lab can be placed instantly after rift jumping

### ISSUE THREAD

**Issue by Kaidenalex** [KnuckleCracker/CW4-bug-tracker#877]
When the rift lab dies, there is usually a 20 second delay before rematerializing. However, when you rift jump, the delay isn't there, and this allows you to instantly place a rift lab anywhere it can be placed. This exploit allows for faster optional objective times, which could be unfair.

**Comment by knucracker** [comment]
This is sort of kinda on purpose.  In the alternative you are forced to wait 20 seconds after a rift jump, which mean you can't 'Continue Playing' and immediately place the lab back on the map (you have to wait 20 seconds which will lead to potentially failed nullifiers, etc).  So the solution was to allow a user initiated rift jump to not incur the same penalty as an emergency rift jump due to the base being damaged.
