### ISSUE TITLE
[bug] Creeper wave equation is not isotropic

### ISSUE THREAD

**Issue by pimlu** [KnuckleCracker/CW4-bug-tracker#89]
Hey, I noticed this simulation artifact coming out of the waves when I was playing: (in diagonal directions, the wave is taller)
![artifact](https://user-images.githubusercontent.com/9065548/96067111-fed8b480-0e66-11eb-9a4c-d50f0afe555a.png)
I'm writing this bug assuming it's not intentional, because I recognized the same issue in a wave equation simulation I did years back.

![laplacian](https://user-images.githubusercontent.com/9065548/96067187-2d568f80-0e67-11eb-9818-5c6ffb40ab78.png)

The problem for me was that the standard 5-point difference formula for the discrete Laplacian is not isotropic. The solution is to use the 9-point Laplacian operator instead of the 5-point:

![stencil](https://user-images.githubusercontent.com/9065548/96067232-45c6aa00-0e67-11eb-88d9-00308f9e74ef.PNG)
The formula for this comes from the first page of [this document](https://docs.lib.purdue.edu/cgi/viewcontent.cgi?article=1928&context=cstech) and is a combination of two different 5-point Laplacians, one of them being on the diagonal. The diagonal stencil has to be halved because of the increased distance between the points.

I picked an alpha of 1/2 for the screenshot I made which looks good to me but I've seen multiple places say 1/3 is optimal, not sure why.

**Additional context**
I've been playing CW games since the very first one when I was a kid back in the flash era, I think it probably contributed to me studying math just because I got interested in fluid simulations lol! I'm a huge fan, excited for CW4. Particle Fleet was fantastic too. Looking forward to the release!

**Comment by grabz-dev** [comment]
I am not qualified enough to comment on this, but I just want to point out that the Creeper simulation has been optimized to a fairly extreme degree, so if you know how this is fixed without a performance penalty - great, but if there's a performance penalty then it might not be worth implementing.

**Comment by pimlu** [comment]
Yeah, that is a good question to ask, it would depend on the Creeper simulation code.  Going off what you're saying, if it's optimized for the 5 point specifically, this does add 4 points to the calculation so it would be a question of whether the Laplacian is the bottleneck in the simulation - if it's not, implementing this shouldn't have a major performance penalty.

If CW4 already uses a 9x9 kernel/stencil to find the Laplacian the numbers would just have to be changed to this:
![image](https://user-images.githubusercontent.com/9065548/96132503-7b4faf80-0ec8-11eb-9308-30695daf5bbf.png)

**Comment by knucracker** [comment]
Yeah, I use 4 points (for performance). It's even more restrictive than that. I only use 2 points, in different phases (at different times). It works out to 4 points, but it spreads the computation out and cuts down on memory access at the time that other things are accessing memory in the game.  CW1 used 8 points (believe it or not). I switched to 4 later on because the game scale became more important than accuracy. The wave mechanic also means I have to access memory at a couple of locations per 'point'. It's all very fast, but with 65536 max points updating at 30 fps, it's a tight performance container. This assumes, naturally, weaker CPU machines and that there is a whole lot of other demands on the CPUfrom the rest of the game logic.

For future work, I want to return to a more accurate sim, and move the computations off CPU.  Thanks for this overview, though. I remember playing with various multipliers 0.5, 0.3, etc. on the corner points in the past.
