### ISSUE TITLE
[bug] Minimap flashes when UI hidden

### ISSUE THREAD

**Issue by Karsten75** [KnuckleCracker/CW4-bug-tracker#90]
Bug reported by Discord User Justice41. 

https://discordapp.com/channels/192420539204239361/368747848046739456/766538787220095006

The zipped file is a video of the issue: 
[cw4_bug.zip](https://github.com/KnuckleCracker/CW4-bug-tracker/files/5393417/cw4_bug.zip)

Would seem that if UI is hidden, attempts to resize the minimap result in the minimap flashing.

**Comment by knucracker** [comment]
The background of the circular area was not set to raycast. This is because unity only supports rectangular raycast images. I didn't want the top left corner to get in the way for clicking. So I've left it set to not raycast. When set to hidden ui, and the player hovers over the activation area, that will set the circular background to raycast. That in turn prevents the rapid on/off cycle. When the area is exited, the circular area is set back to not raycast.
