### ISSUE TITLE
[Bug.Minor] Planet theme backgrounds not centered on map.

### ISSUE THREAD

**Issue by RealArgonwolf** [KnuckleCracker/CW4-bug-tracker#903]
The planet background textures don't center themselves around the map. Still present in Mverse beta.

**Comment by knucracker** [comment]
Somewhere along the way, passing in the map width/depth to the shader got removed.  So the planet background shader was assuming all missions were 256x192.  I've corrected it so that the actual map dimensions are passed into the shader. It should now draw a planet background disk that always encompasses the actual map.
