### ISSUE TITLE
Make trace work to rpl.txt file

### ISSUE THREAD

**Issue by knucracker** [KnuckleCracker/CW4-bug-tracker#917]
Hook up the 'debugtext' handler so it works for regular scripts (not just console scripts). This will cause trace statements to go to RPL.txt and for other warnings to appear there as well.  As usual, only work when in edit mode (same as print commands).

**Comment by zer0ner** [comment]
The supplied solution here is not sufficient.  Only logging when the editor is enabled excludes the following use-cases:

1. Playtesting.  The editor isn't active when playing normally.  Therefore no errors are logged anywhere.
2. GetEditMode() 4RPL detection code.  If there is code that behaves differently when the editor is active, then the problem area within the code might not even execute when the editor is active.  Therefore, it is possible for errors to exist that are never logged.

A simple alert text that unobtrusively overlays on the game describing the problem and an alert sound for the first detected 4RPL error would solve both cases AND alert to the fact that there is a problem in the first place.  Not all bugs are immediately obvious.

4RPL code being postfix notation keeps resulting in gotchas for me like stack errors that go undetected until after a map is published.  There are ways to transform infix notation into postfix notation and would result in a far better coding experience for the vast majority of existing programmers and software developers.  Requiring postfix notation at the coding level and not detecting stack problems in the 4RPL compiler is guaranteed to result in unfortunate errors at runtime.  The community's seen a number of broken units and code because of postfix vs. infix notation.  I've done that myself many times and still managed to miss a spot here or there in published maps.  There are very few postfix notation languages in existence - HP calculators (I've never owned one), Forth, and now 4RPL are the only ones that I'm aware of.  Postfix notation has its advantages for tokenizing each line of input but it's just not natural to me.  If the 4RPL opcode compiler was better at detecting stack errors, then runtime error handling would be less of an issue but still a good idea.
