### ISSUE TITLE
Colony map settings

### ISSUE THREAD

**Issue by MadVandal** [KnuckleCracker/CW4-bug-tracker#940]
Issues on Colony Map screen:
1) My last colony map sort choice keeps getting unchecked and reverting back to "Newest" when I finish a map or the game is restarted.  
2) Author search isn't a wildcard/string contains search. For example a search for "Tricky" should match "TrickyCorp" but it doesn't.

**Comment by knucracker** [comment]
The sort option was not being saved, fixed in 2.0.3 and later.
For the author filter, I have added wildcard support.  So, *cor* will now match TrickyCorp and Cornucanis maps, for instance.  I didn't want to make the string always be a wildcard since that can make it more difficult to find authors that have short names (there used to be a user named 'J' in previous games for instance).
