### ISSUE TITLE
[4RPL] Detect old cpack folders in editor project or _UNKNOWN and give replace prompt if found

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#970]
Currently the game gives a [replace scripts] prompt when a cpack is imported while a cpack with the same guid is already in the mission. It in theory would be great if the game could detect lingering cpacks in the folder while they are not imported in the mission and give a similar prompt. It seems like it would solve both lingering cpack scripts in editor project folders as well as having to wipe the _UNKNOWN folder frequently

**Comment by knucracker** [comment]
I've made it so the game detects if there are lingering scripts on disk during cpack import.  If so, it will prompt the user during the import to continue and if they do, the scripts on disk will be overwritten.  This is similar to what happens when importing a cpack that is already loaded in a map.  The difference being that the game now looks on disk to see of there are some scripts regardless if the cpack is loaded in the map or not.
