### ISSUE TITLE
[4RPL][Bug] :Awake in pre-placed units runs before :Awake in Pre global scripts

### ISSUE THREAD

**Issue by grabz-dev** [KnuckleCracker/CW4-bug-tracker#989]
![image](https://user-images.githubusercontent.com/51026936/135298713-65ca4656-133b-42ac-b441-42a697c9eb51.png)

Recycler.4rpl is part of a pre-placed unit
PreGameSettingsManager.4rpl is a Pre exec global script
The stuff at the bottom after it are also different Pre exec scripts on different CPACKs.

I worked around this and don't need this fixed, but was told to create a ticket by K75:
> that sounds like a bug, but so high-risk to fix at this stage
> open the issue anyway, let KC make the call

**Comment by knucracker** [comment]
It looks like the Awake functions for pre-existing units get run during the map load process.  Awake functions in in global scripts don't do this.  They run only on game update frames.  So even if you set a global script to run when paused, it will only run on the first game tick which happens after the units are loaded.  Note that if you don't set a global script to run when paused, the Awake function will not get called until the game is unpaused.  This is different from units where Awake runs on load (which is before the game is unpaused naturally).

Were the game not yet released I would change this behavior for globabl scripts.  But, if I change it now I could break any maps where the global scripts rely on the unit awake calls having been run already.  Say, there is a global script that looks for preexisting unit on a map that have registered themselves in their Awake functions.

So because of this possibility of breaking existing maps, I'll leave it as is.

**Comment by Karsten75** [comment]
> Were the game not yet released I would change this behavior for globabl[sic] scripts. But, if I change it now I could break any maps where the global scripts rely on the unit awake calls having been run already. Say, there is a global script that looks for preexisting unit on a map that have registered themselves in their Awake functions.

This would also introduce additional complexity, even if one were to start on a clean slate, so to speak. In the case outlined above, the units may not be on the map yet, since "Pre-" by my reckoning would run prior to unit creation? Otherwise it's be "run before any frame, but after units are created" or some-such

And then, by rights, "Pre-"  would not run again, so one would have to create special exits for "Pre-init, post-init, and leave the current "pre- and Post processing routines in place.  Meaning any script requiring processing of units prior to first frame would have to run in "post-init"

Whole tier of additional complexity.
